"""
QORA TECH - Solar Smart Cold Storage
Crop Database & Agronomical Storage Specifications for North Eastern Region (NER) of India
"""

INITIAL_CROPS = [
    {
        "id": "crop_cabbage",
        "name": "Cabbage",
        "scientific_name": "Brassica oleracea var. capitata",
        "category": "Brassica / Cole Crop",
        "recommended_zone": "ZONE 2",
        "target_zone_id": 2,
        "min_temp": 0.0,
        "max_temp": 2.0,
        "optimal_temp": 1.0,
        "min_humidity": 95,
        "max_humidity": 98,
        "shelf_life_ambient": "4–6 Days",
        "shelf_life_cold": "60–90 Days",
        "image_url": "static/images/crops/cabbage.jpg",
        "source_info": "ICAR-RC for NEH Region / NHB Standards",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Rabi"],
        "advisory": "Store in Zone 2 (0–2°C) with high humidity (95–98%) to prevent moisture loss and outer leaf yellowing."
    },
    {
        "id": "crop_cauliflower",
        "name": "Cauliflower",
        "scientific_name": "Brassica oleracea var. botrytis",
        "category": "Brassica / Cole Crop",
        "recommended_zone": "ZONE 2",
        "target_zone_id": 2,
        "min_temp": 0.0,
        "max_temp": 2.0,
        "optimal_temp": 1.0,
        "min_humidity": 95,
        "max_humidity": 98,
        "shelf_life_ambient": "3–5 Days",
        "shelf_life_cold": "21–30 Days",
        "image_url": "static/images/crops/cauliflower.jpg",
        "source_info": "National Horticulture Board (NHB) Storage Standards",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Spring"],
        "advisory": "Keep curds covered from light. Sensitive to ethylene; avoid storing near ripening tomatoes."
    },
    {
        "id": "crop_tomato",
        "name": "Tomato",
        "scientific_name": "Solanum lycopersicum",
        "category": "Solanaceous Fruit",
        "recommended_zone": "ZONE 3",
        "target_zone_id": 3,
        "min_temp": 8.0,
        "max_temp": 12.0,
        "optimal_temp": 10.0,
        "min_humidity": 85,
        "max_humidity": 90,
        "shelf_life_ambient": "5–7 Days",
        "shelf_life_cold": "21–28 Days",
        "image_url": "static/images/crops/tomato.jpg",
        "source_info": "NERAMAC Post-Harvest Protocol",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Summer", "Monsoon"],
        "advisory": "Do NOT store below 8°C to prevent chilling injury. Produces ethylene; requires active ventilation."
    },
    {
        "id": "crop_green_chilli",
        "name": "Green Chilli",
        "scientific_name": "Capsicum annuum",
        "category": "Spices / Solanaceous",
        "recommended_zone": "ZONE 3",
        "target_zone_id": 3,
        "min_temp": 8.0,
        "max_temp": 11.0,
        "optimal_temp": 9.5,
        "min_humidity": 90,
        "max_humidity": 95,
        "shelf_life_ambient": "4–6 Days",
        "shelf_life_cold": "20–30 Days",
        "image_url": "static/images/crops/green_chilli.jpg",
        "source_info": "Spices Board India / Assam Agribusiness",
        "season": "Summer",
        "suitable_seasons": ["Summer", "Monsoon", "Year-round"],
        "advisory": "Chilling injury occurs below 7°C causing calyx discoloration. Keep in Zone 3 at 8–10°C."
    },
    {
        "id": "crop_french_beans",
        "name": "French Beans",
        "scientific_name": "Phaseolus vulgaris",
        "category": "Legume / Pod",
        "recommended_zone": "ZONE 1",
        "target_zone_id": 1,
        "min_temp": 4.0,
        "max_temp": 7.5,
        "optimal_temp": 5.0,
        "min_humidity": 90,
        "max_humidity": 95,
        "shelf_life_ambient": "3–4 Days",
        "shelf_life_cold": "14–21 Days",
        "image_url": "static/images/crops/french_beans.jpg",
        "source_info": "NER Agronomy Guide / ICAR Barapani",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Spring"],
        "advisory": "Store in Zone 1 (4–7.5°C). Susceptible to chilling russeting if stored under 3°C."
    },
    {
        "id": "crop_leafy_veg",
        "name": "Leafy Vegetables (Spinach / Lai Saag)",
        "scientific_name": "Spinacia oleracea / Brassica juncea",
        "category": "Leafy Greens",
        "recommended_zone": "ZONE 2",
        "target_zone_id": 2,
        "min_temp": 0.0,
        "max_temp": 2.0,
        "optimal_temp": 0.5,
        "min_humidity": 95,
        "max_humidity": 100,
        "shelf_life_ambient": "1–2 Days",
        "shelf_life_cold": "10–14 Days",
        "image_url": "static/images/crops/leafy_veg.jpg",
        "source_info": "Assam Agricultural University (AAU) Jorhat",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Autumn"],
        "advisory": "High respiration rate requires immediate pre-cooling in Zone 2 with near 100% RH."
    },
    {
        "id": "crop_brinjal",
        "name": "Brinjal (Eggplant)",
        "scientific_name": "Solanum melongena",
        "category": "Solanaceous Fruit",
        "recommended_zone": "ZONE 3",
        "target_zone_id": 3,
        "min_temp": 9.0,
        "max_temp": 12.5,
        "optimal_temp": 10.5,
        "min_humidity": 90,
        "max_humidity": 95,
        "shelf_life_ambient": "3–5 Days",
        "shelf_life_cold": "14–20 Days",
        "image_url": "static/images/crops/brinjal.jpg",
        "source_info": "ICAR-NEH Post Harvest Tech",
        "season": "Summer",
        "suitable_seasons": ["Summer", "Monsoon", "Rabi"],
        "advisory": "Very prone to surface pitting and seed browning below 8°C. Store in Zone 3."
    },
    {
        "id": "crop_carrot",
        "name": "Carrot",
        "scientific_name": "Daucus carota subsp. sativus",
        "category": "Root Crop",
        "recommended_zone": "ZONE 2",
        "target_zone_id": 2,
        "min_temp": 0.0,
        "max_temp": 2.0,
        "optimal_temp": 0.5,
        "min_humidity": 98,
        "max_humidity": 100,
        "shelf_life_ambient": "5–8 Days",
        "shelf_life_cold": "90–120 Days",
        "image_url": "static/images/crops/carrot.jpg",
        "source_info": "National Centre for Cold-chain Development (NCCD)",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Spring"],
        "advisory": "Extremely sensitive to ethylene which makes carrots bitter. Keep in Zone 2 with clean air/UV-C."
    },
    {
        "id": "crop_potato",
        "name": "Potato",
        "scientific_name": "Solanum tuberosum",
        "category": "Tuber / Root",
        "recommended_zone": "ZONE 3",
        "target_zone_id": 3,
        "min_temp": 8.0,
        "max_temp": 12.0,
        "optimal_temp": 9.0,
        "min_humidity": 90,
        "max_humidity": 95,
        "shelf_life_ambient": "14–21 Days",
        "shelf_life_cold": "120–180 Days",
        "image_url": "static/images/crops/potato.jpg",
        "source_info": "CPRI Shimla / NER Regional Station Shillong",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Post-Harvest"],
        "advisory": "Storing below 7°C causes cold-sweetening (sugar accumulation). Zone 3 (8–12°C) is ideal for table potatoes."
    },
    {
        "id": "crop_capsicum",
        "name": "Capsicum (Bell Pepper)",
        "scientific_name": "Capsicum annuum var. grossum",
        "category": "Solanaceous Fruit",
        "recommended_zone": "ZONE 1",
        "target_zone_id": 1,
        "min_temp": 7.0,
        "max_temp": 9.0,
        "optimal_temp": 7.5,
        "min_humidity": 90,
        "max_humidity": 95,
        "shelf_life_ambient": "4–6 Days",
        "shelf_life_cold": "21–28 Days",
        "image_url": "static/images/crops/capsicum.jpg",
        "source_info": "NER Horticulture Development Board",
        "season": "Monsoon",
        "suitable_seasons": ["Monsoon", "Year-round", "Polyhouse"],
        "advisory": "Maintain 7–9°C in upper Zone 1. Chilling injury with calyx rot occurs below 5°C."
    },
    {
        "id": "crop_ginger",
        "name": "Ginger (Nadia / Maran)",
        "scientific_name": "Zingiber officinale",
        "category": "Rhizome / High Value NER Spice",
        "recommended_zone": "ZONE 3",
        "target_zone_id": 3,
        "min_temp": 12.0,
        "max_temp": 14.0,
        "optimal_temp": 12.5,
        "min_humidity": 85,
        "max_humidity": 90,
        "shelf_life_ambient": "10–14 Days",
        "shelf_life_cold": "120–150 Days",
        "image_url": "static/images/crops/ginger.jpg",
        "source_info": "ICAR Nagaland / Spices Board",
        "season": "Winter",
        "suitable_seasons": ["Winter", "Post-Harvest"],
        "advisory": "Ginger is tropical; never store below 12°C to prevent chilling decay and skin darkening. Store in Zone 3."
    },
    {
        "id": "crop_bhut_jolokia",
        "name": "Bhut Jolokia (Ghost Pepper)",
        "scientific_name": "Capsicum chinense",
        "category": "GI Tagged NER King Chilli",
        "recommended_zone": "ZONE 3",
        "target_zone_id": 3,
        "min_temp": 8.0,
        "max_temp": 11.0,
        "optimal_temp": 9.0,
        "min_humidity": 90,
        "max_humidity": 95,
        "shelf_life_ambient": "3–5 Days",
        "shelf_life_cold": "25–35 Days",
        "image_url": "static/images/crops/bhut_jolokia.jpg",
        "source_info": "Assam Agricultural University GI Cell",
        "season": "Monsoon",
        "suitable_seasons": ["Monsoon", "Autumn"],
        "advisory": "High value export crop. Retains capsaicin pungency and firm texture at 8–10°C in Zone 3."
    }
]

def get_crops_dict():
    return {c["id"]: c for c in INITIAL_CROPS}

def get_crop_by_id(crop_id):
    for c in INITIAL_CROPS:
        if c["id"] == crop_id or c["name"].lower() == crop_id.lower():
            return c
    return None
